#!/bin/sh

#
# Copyright © 2015-present The Gradle In Action book Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# $Revision: 6ee975c23a0d8295e9f8d8e127a9e0ca9a088a9d $
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASENAME=${0##*/}
# shellcheck disable=SC2034
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if $cygwin || $msys ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    # shellcheck disable=SC2034
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Read LOGGING_LEVEL and JAVA_OPTS from gradle.properties
if [ -r "$HOME/.gradle/gradle.properties" ] ; then
    # shellcheck disable=SC1091
    . "$HOME/.gradle/gradle.properties" 2>/dev/null
fi

if [ -r "${APP_HOME}.gradle/gradle.properties" ] ; then
    # shellcheck disable=SC1091
    . "${APP_HOME}.gradle/gradle.properties" 2>/dev/null
fi

if [ -r "${APP_HOME}/gradle.properties" ] ; then
    # shellcheck disable=SC1091
    . "${APP_HOME}/gradle.properties" 2>/dev/null
fi

# Default values
: "${LOGGING_LEVEL:=LIFECYCLE}"
: "${JAVA_OPTS:=-Xmx64m -Xms64m}"

# Ensure minimum required memory is set
JAVA_OPTS="$JAVA_OPTS -Xms64m"

# Need a new enough Java version
JAVA_MIN_VERSION=1.8

# Attempt to determine the Java under which this script is actually running
if [ -n "$JAVA_HOME" ] ; then
    JAVA_HOME=$( cd "$JAVA_HOME" && pwd -P )
    if [ ! -d "$JAVA_HOME" ] || [ ! -x "$JAVA_HOME/bin/java" ] ; then
        die "Invalid JAVA_HOME: $JAVA_HOME"
    fi
    JAVA_EXE="$JAVA_HOME/bin/java"
else
    # If JAVA_HOME is not set, then use `java` in the PATH
    JAVA_EXE=java
    # Try to determine JAVA_HOME from the location of `java` in the PATH
    if command -v java >/dev/null 2>&1 ; then
        JAVA_EXE=$( command -v java )
    else
        die "java is not in the PATH, is the JDK installed?"
    fi
fi

# Verify the Java version
JAVA_VERSION=$(
    "$JAVA_EXE" -version 2>&1 |
    sed -E -n 's/.*version "([^.-]*).*"/\1/p'
)
if [ -z "$JAVA_VERSION" ] || [ "$JAVA_VERSION" -lt "$JAVA_MIN_VERSION" ] ; then
    die "Java $JAVA_MIN_VERSION or newer is required to run Gradle, but you are running version $JAVA_VERSION"
fi

# Increase the maximum file descriptors if we can
if ! $cygwin && ! $darwin && ! $msys ; then
    case $MAX_FD in #(
      maximum)
        # In POSIX sh, ulimit -H is undefined - it's a bash-ism
        # shellcheck disable=SC2039
        MAX_FD=$( ulimit -H -n )
        if [ $? -eq 0 ] ; then
            # In POSIX sh, ulimit -n is undefined - it's a bash-ism
            # shellcheck disable=SC2039
            ulimit -n $MAX_FD
        else
            warn "Could not query the maximum file descriptor limit"
        fi
    esac
fi

# Collect all arguments for the java command:
#   * Add the minimum required Java version
#   * Add all the -DjavaProperty=value arguments
#   * Add all the -Xoption arguments
#   * Add all the -Dorg.gradle.property=value arguments
#   * Set the main Gradle class
set -- \
    -javaagent:"${APP_HOME}lib/gradle-launcher-8.2.jar" \
    -Xms64m \
    -Dorg.gradle.wrapper.native=true \
    -Dorg.gradle.daemon=false \
    -Dorg.gradle.logging.level="$LOGGING_LEVEL" \
    -Dorg.gradle.configureondemand=true \
    "$JAVA_OPTS" \
    -cp "${APP_HOME}lib/gradle-launcher-8.2.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Use "exec" to replace the process and avoid creating a new one
exec "$JAVA_EXE" "$@"